{
 "title": "Vendor Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Issuer Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Issuer Network (KiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"issuer\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Input"
    },
    {
     "expr": "sum by (name) (\n  rate(container_network_transmit_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"issuer\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Issuer Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  container_label_com_docker_compose_service=\"issuer\",\n  image!=\"\"\n} / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issuer CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\n  job=\"cadvisor\",\n  container_label_com_docker_compose_service=\"issuer\",\n  image!=\"\"\n}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issuer Network (KiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"redis-issuer\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Input"
    },
    {
     "expr": "sum by (name) (\n  rate(container_network_transmit_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"issuer\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Issuer Redis Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  container_label_com_docker_compose_service=\"redis-issuer\",\n  image!=\"\"\n} / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issuer Redis CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\n  job=\"cadvisor\",\n  name=\"nanomoni-redis-issuer-1\",\n  image!=\"\"\n}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Client Network (KiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"client\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Input"
    },
    {
     "expr": "sum by (name) (\n  rate(container_network_transmit_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"client\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Client Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  container_label_com_docker_compose_service=\"client\",\n  image!=\"\"\n} / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\n  container_label_com_docker_compose_service=\"client\",\n  image!=\"\"\n}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Vendor Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Vendor Network (KiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"vendor\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Input"
    },
    {
     "expr": "sum by (name) (\n  rate(container_network_transmit_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"vendor\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Vendor Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  container_label_com_docker_compose_service=\"vendor\",\n  image!=\"\"\n} / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\n  job=\"cadvisor\",\n  name=\"nanomoni-vendor-1\",\n  image!=\"\"\n}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Vendor Network (KiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"redis-vendor\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Input"
    },
    {
     "expr": "sum by (name) (\n  rate(container_network_transmit_bytes_total{\n    job=\"cadvisor\",\n    container_label_com_docker_compose_service=\"vendor\",\n    image!=\"\"\n  }[1m])\n) / 1024",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Vendor Redis Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  container_label_com_docker_compose_service=\"redis-vendor\",\n  image!=\"\"\n} / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issuer Redis CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\n  job=\"cadvisor\",\n  name=\"nanomoni-redis-vendor-1\",\n  image!=\"\"\n}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TPS Métrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Vendor Payment TPS (success)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 44 },
   "targets": [
    {
     "expr": "rate(payment_requests_total{job=\"vendor-api\", status=\"success\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(payment_requests_total{job=\"vendor-api\", status=\"client_error\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(payword_payment_requests_total{job=\"vendor-api\", status=\"client_error\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(payword_payment_requests_total{job=\"vendor-api\", status=\"success\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(paytree_std_payment_requests_total{job=\"vendor-api\", status=\"success\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(paytree_std_payment_requests_total{job=\"vendor-api\", status=\"success\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(paytree_first_opt_payment_requests_total{job=\"vendor-api\", status=\"success\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(paytree_first_opt_payment_requests_total{job=\"vendor-api\", status=\"success\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor Payment Duration Average (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(rate(payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Signature P99"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Signature P95"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Signature P50"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(payword_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Payword P99"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(payword_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Payword P95"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(payword_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Payword P50"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(paytree_std_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Paytree P99"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(paytree_std_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Paytree P95"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(paytree_std_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "Paytree P50"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(paytree_first_opt_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(paytree_first_opt_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(paytree_first_opt_payment_request_duration_milliseconds_bucket{job=\"vendor-api\", status=\"success\"}[1m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frequency Distribution of Payment Latency",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 18, "x": 3, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(payment_request_duration_milliseconds_bucket{job=\"vendor-api\",status=\"success\"}) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}