@startuml Phase1a_Registration

!theme plain
autonumber

hide footbox

actor "Cliente" as Client
participant "API do Emissor" as Issuer
database "BD do Emissor\n(Redis)" as IssuerDB

Client -> Issuer: Enviar requisição de cadastro
activate Issuer

Issuer -> Issuer: Validar requisição
Issuer -> IssuerDB: Criar conta
IssuerDB --> Issuer: Conta

Issuer --> Client: Cadastro confirmado
deactivate Issuer

@enduml
