@startuml Phase2a_First_Payment

!theme plain
autonumber

hide footbox

actor "Cliente" as Client
participant "API do Vendedor" as Vendor
database "BD do Vendedor\n(Redis)" as VendorDB
participant "API do Emissor" as Issuer
database "BD do Emissor\n(Redis)" as IssuerDB

Client -> Client: Construir pagamento

Client -> Vendor: Enviar pagamento
activate Vendor

Vendor -> VendorDB: Buscar canal
VendorDB --> Vendor: nenhum

Vendor -> Issuer: Buscar canal
activate Issuer
Issuer -> IssuerDB: Obter canal
IssuerDB --> Issuer: Canal
Issuer --> Vendor: Canal
deactivate Issuer

Vendor -> Vendor: Validar pagamento

Vendor -> VendorDB: Armazenar canal e pagamento
VendorDB --> Vendor: 

Vendor --> Client: Criado
deactivate Vendor

@enduml
