@startuml Phase2_Payments

!theme plain
autonumber

hide footbox

actor "Cliente" as Client
participant "API do Vendedor" as Vendor
database "BD do Vendedor\n(Redis)" as VendorDB
participant "API do Emissor" as Issuer
database "BD do Emissor\n(Redis)" as IssuerDB

loop para cada pagamento
    Client -> Client: Construir pagamento

    Client -> Vendor: Enviar pagamento
    activate Vendor

    Vendor -> VendorDB: Buscar canal
    
    alt canal não encontrado (Primeiro Pagamento)
        VendorDB --> Vendor: nenhum

        Vendor -> Issuer: Buscar canal
        activate Issuer
        Issuer -> IssuerDB: Obter canal
        IssuerDB --> Issuer: Canal
        Issuer --> Vendor: Canal
        deactivate Issuer

        Vendor -> Vendor: Validar pagamento

        Vendor -> VendorDB: Armazenar canal e pagamento
        VendorDB --> Vendor: 
    else canal encontrado (Pagamento Subsequente)
        VendorDB --> Vendor: Canal e último pagamento
        
        Vendor -> Vendor: Verificar pagamento recebido
        
        Vendor -> VendorDB: Atualizar pagamento
        VendorDB --> Vendor: 
    end

    Vendor --> Client: Sucesso / Criado
    deactivate Vendor
end

@enduml
