@startuml Phase1b_Channel_Opening

!theme plain
autonumber

hide footbox

actor "Client" as Client
participant "Vendor" as Vendor
participant "Issuer API" as Issuer
database "Issuer DB\n(Redis)" as IssuerDB

Client -> Vendor: Get vendor public key
Vendor --> Client: Vendor public key
Client -> Client: Prepare channel opening request

Client -> Issuer: Send Open Request
activate Issuer

Issuer -> Issuer: Verify request
Issuer -> IssuerDB: Lock funds and create channel
IssuerDB --> Issuer: 

Issuer --> Client: Channel opened
deactivate Issuer

@enduml
