@startuml Phase2a_First_Payment

!theme plain
autonumber

hide footbox

actor "Client" as Client
participant "Vendor API" as Vendor
database "Vendor DB\n(Redis)" as VendorDB
participant "Issuer API" as Issuer
database "Issuer DB\n(Redis)" as IssuerDB

Client -> Client: Build payment

Client -> Vendor: Submit Payment
activate Vendor

Vendor -> VendorDB: Fetch channel
VendorDB --> Vendor: none

Vendor -> Issuer: Fetch channel
activate Issuer
Issuer -> IssuerDB: Get channel
IssuerDB --> Issuer: Channel
Issuer --> Vendor: Channel
deactivate Issuer

Vendor -> Vendor: Validate payment

Vendor -> VendorDB: Store channel and payment
VendorDB --> Vendor: 

Vendor --> Client: Created
deactivate Vendor

@enduml
