@startuml Phase2b_Subsequent_Payments

!theme plain
autonumber

hide footbox

actor "Client" as Client
participant "Vendor API" as Vendor
database "Vendor DB\n(Redis)" as VendorDB

loop for each subsequent payment

    Client -> Client: Build payment

    Client -> Vendor: Submit Payment
    activate Vendor

    Vendor -> VendorDB: Fetch channel and payment
    VendorDB --> Vendor: channel/payment data

    Vendor -> Vendor: Verify incoming payment

    Vendor -> VendorDB: Update payment
    VendorDB --> Vendor: OK
    
    Vendor --> Client: payment confirmation
    deactivate Vendor

end

@enduml
