@startuml Phase3a_Closure_Initiation

!theme plain
autonumber

hide footbox

actor "Client" as Client
participant "Vendor API" as Vendor
database "Vendor DB\n(Redis)" as VendorDB

Client -> Vendor: Request Channel Closure
activate Vendor

Vendor -> VendorDB: Fetch channel and payment
VendorDB --> Vendor

Vendor -> Vendor: Prepare settlement request

Vendor -> Issuer: Send Settlement Request
activate Issuer

Issuer -> IssuerDB: Get channel
IssuerDB --> Issuer: 

Issuer -> Issuer: Verify request

Issuer -> IssuerDB: Update Accounts
IssuerDB --> Issuer: 
Issuer -> IssuerDB: Update channel as closed
IssuerDB --> Issuer: 

Issuer --> Vendor:
deactivate Issuer

Vendor -> VendorDB: Update channel as closed
VendorDB --> Vendor: 
Vendor --> Client
deactivate Vendor

@enduml
