@startuml System_Overview

!theme plain
skinparam backgroundColor white
skinparam componentStyle rectangle
skinparam padding 5
skinparam BoxPadding 5
skinparam RectanglePadding 5
skinparam NotePadding 2
skinparam RectangleBorderThickness 2
skinparam Shadowing false
skinparam ArrowThickness 2

hide footbox

actor "**Cliente**" as Client #FFE6B3
participant "**Vendedor**" as Vendor #E6F3E6
participant "**Emissor**" as Issuer #FFE6E6

note over Client, Issuer: **1. Cadastro**
Client -> Issuer: Requisição de cadastro
activate Issuer
Issuer -> Issuer: Validar requisição
Issuer --> Client: Conta criada
deactivate Issuer

note over Client, Issuer: **2. Abertura de Canal**
Client -> Issuer: Requisição de abertura de canal
activate Issuer
Issuer -> Issuer: Validar requisição
Issuer -> Issuer: Bloquear fundos
Issuer --> Client: Canal aberto
deactivate Issuer


note over Client, Vendor: **3. Fluxo de Pagamentos**
Client -> Vendor: Iniciar fluxo de pagamentos
activate Vendor

loop 9.999 vezes
  Client -> Vendor: Enviar pagamento
  Vendor --> Client: Pagamento aceito
end

deactivate Vendor


note over Vendor, Issuer: **4. Liquidação do Canal**
Vendor -> Issuer: Iniciar liquidação
activate Issuer
Issuer -> Issuer: Validar liquidação
Issuer -> Issuer: Transferir fundos
Issuer --> Vendor: Liquidação concluída
deactivate Issuer

Vendor --> Client: Canal fechado

@enduml
